[build]
  command = "CI= npm run build"
  publish = "build"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  publish = "Portfolio-Main/build"

[context.branch-deploy]
  command = "npm run build"
  publish = "Portfolio-Main/build"
